// generated by pcg, DO NOT modify manually.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Collections;
using XLua;


namespace Protocol {
	public enum COM_GAME_FRAMEWORK {
		eCOM_GAME_FRAMEWORK_BEGIN = 0,

		eC2S_Login = 1,
		eS2C_Json = 2,

		eCOM_GAME_FRAMEWORK_END,
		eCOM_GAME_FRAMEWORK_MAX
	}
    [LuaCallCSharp]
    public class ProtocolBase{
        private int proto;
        public ProtocolBase(Int32 proto) {
            this.proto = proto;
        }

        public virtual void Pack(MsgPack packer, bool clear = true) {
            if (clear) packer.Reset();
            packer.PackProtoID(this.proto);
        }

    }

}

namespace Protocol {
    [LuaCallCSharp]
	public class C2S_Login : ProtocolBase {
		public String token;

		public C2S_Login() : base((Int32)COM_GAME_FRAMEWORK.eC2S_Login) {
		}
        public override void Pack(MsgPack packer, bool clear = true) {
			base.Pack(packer,clear);

			if (token == null)
                packer.PackString("");
			else {
                packer.PackString(token);
			}
		}

		public void Unpack(MsgPack packer) {
            this.token = packer.UnPackString();
		}

	}

}

namespace Protocol {
    [LuaCallCSharp]
    public class S2C_Json : ProtocolBase {
		public String json;

		public S2C_Json() : base((Int32)COM_GAME_FRAMEWORK.eS2C_Json) {
		}
        public override void Pack(MsgPack packer, bool clear = true) {
            base.Pack(packer, clear);

            if (json == null)
                packer.PackString("");
            else {
                packer.PackString(json);
            }
		}

        public void Unpack(MsgPack packer) {
            this.json = packer.UnPackString();
        }

	}

}
